name: CI

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo the env var
        run: echo "$TEST_ABC"
        env: 
          TEST_ABC: ${{ vars.ABC }}
